version: "3.8"

services:
  beets-manager:
    image: ghcr.io/${GH_USERNAME:-your-github-username}/${GH_REPONAME:-your-repo-name}:${IMAGE_TAG:-latest}
    container_name: beets-manager
    restart: unless-stopped
    ports:
      - "${APP_PORT:-5000}:8000"
    volumes:
      - ${BEETS_CONFIG_DIR_HOST:-./config}:/config
      - ${MUSIC_DIR_HOST:-./music}:/music
      - ${DOWNLOAD_DIR_HOST:-./downloads}:/downloads
    environment:
      # User/group IDs for file permissions
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      # Beets configuration
      - BEETS_CONFIG_PATH=/config/config.yaml
      - MUSIC_DIRECTORY_CONTAINER=/music
      - DOWNLOAD_DIRECTORY_CONTAINER=/downloads
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
      - SESSION_SECRET=${SESSION_SECRET:-please_change_this_secret_key}
      # Add Python environment variables to prevent buffering and improve memory usage
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    # Add resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
