version: "3.8"

services:
  beets-manager:
    image: ghcr.io/geleeroyale/beetsmanager-latest
    container_name: beets-manager
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8777}:8000"
    volumes:
      - ${BEETS_CONFIG_DIR_HOST:-./config}:/root/.config/beets
      - ${MUSIC_DIR_HOST:-./music}:/music
      - ${DOWNLOAD_DIR_HOST:-./downloads}:/downloads
    environment:
      - BEETS_CONFIG_PATH=/root/.config/beets/config.yaml
      - MUSIC_DIRECTORY_CONTAINER=/music
      - DOWNLOAD_DIRECTORY_CONTAINER=/downloads
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
      - SESSION_SECRET=${SESSION_SECRET:-please_change_this_secret_key}
